import type { Metadata } from "next";
import { Roboto, Anton } from "next/font/google";
import "./globals.css";
import NaviBar from "@/components/Navibar";
import AuthProvider from "@/providers/auth";

const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});


const anton = Anton({
  weight: ["400"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-anton",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${anton.variable} antialiased mx-auto`}
      >
        <AuthProvider>
          <NaviBar />
          <div className="container mx-auto">
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
